gate.example.com:
  build: ./gate
  ports:
    - "8080:8080"
  links:
    - app.example.com
    - auth.example.com

auth.example.com:
  build: ./auth
  expose:
    - "8080"

app.example.com:
  build: ./app
  expose:
    - "8080"